---- FIND THE DATE OF FIRST AND LAST ORDER FIRST AND THE LAST ORDER DATE
--FIND THE DATE OF THE FIRST AND LAST ORDER
-- HOW MANY MONTH OF SALES ARE AVAILABLE
SELECT	
	MIN(order_date) AS FIRST_ORDER_DATE,
	MAX(order_date) AS LAST_ORDER_DATE,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS ORDER_RANGE_MONTH
FROM gold.fact_sales


--- FIND THE YOUNGEST AND OLDEST CUSTOMER
SELECT 
	MIN(birthdate) AS OLDEST_CUSTOMER,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS OLDEST_AGE,
	MAX(birthdate) AS YOUNGEST_CUSTOMER,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS YOUNGEST_AGE
FROM gold.dim_customers
