--- FIND THE TOTAL SALES
SELECT SUM(sales_amount) AS TOTAL_SALES
FROM gold.fact_sales

--- FIND HOW MANY ITEMS ARE SOLD
SELECT SUM(quantity) AS TOTAL_QUANTITY
FROM gold.fact_sales
--- FIND THE AVERAGE SELLING PRICE
SELECT AVG(price) AS AVG_PRICE
FROM gold.fact_sales

--- FIND THE TOTAL NUMBER OF ORDERS
SELECT COUNT(order_number) AS TOTAL_ORDERS
FROM gold.fact_sales


--- FIND THE TOTAL NUMBER OF PRODUCTS
SELECT COUNT(product_number) AS TOTAL_PRODUCTS
FROM gold.dim_products
SELECT COUNT(DISTINCT product_number) AS TOTAL_PRODUCTS
FROM gold.dim_products

--- FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT COUNT(customer_key) AS TOTAL_CUSTOMERS
FROM gold.dim_customers

--- FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAS PLACED AN ORDER
SELECT COUNT(DISTINCT customer_key) AS TOTAL_CUSTOMERS
FROM gold.fact_sales

----GENERATE A REPORT THAT SHOWS ALL THE KEY METRICS OF THE BUSINESS
SELECT 'TOTAL SALES' AS MEASURE_NAME, SUM(sales_amount) AS MEASURE_VALUE FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL QUANTITY' AS MEASURE_NAME, SUM(quantity) AS MEASURE_VALUE FROM gold.fact_sales
UNION ALL
SELECT 'AVG PRICE' AS MEASURE_NAME, AVG(price) AS MEASURE_VALUE FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL ORDERS' AS MEASURE_NAME, COUNT(order_number) AS MEASURE_VALUE FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL PRODUCTS' AS MEASURE_NAME, COUNT(product_number) AS MEASURE_VALUE FROM gold.dim_products
UNION ALL
SELECT 'TOTAL CUSTOMERS' AS MEASURE_NAME, COUNT(customer_key) AS MEASURE_VALUE FROM gold.dim_customers
UNION ALL
SELECT 'TOTAL CUSTOMERS ORDERS' AS MEASURE_NAME, COUNT(customer_key) AS MEASURE_VALUE FROM gold.fact_sales
